package org.demo.model;

// Generated Sep 29, 2014 1:57:16 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.persistence.GeneratedValue;

import java.util.logging.Logger;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "public")
public class Role implements java.io.Serializable
{

   private long id;
   private Integer version;
   private String name;

   private static final Logger LOG = Logger.getLogger(Role.class.getName());

   public Role()
   {
   }

   public Role(long id)
   {
      this.id = id;
   }

   @Id
   @Column(name = "id", unique = true, nullable = false)
   @GeneratedValue
   public long getId()
   {
      return this.id;
   }

   public void setId(long id)
   {
      this.id = id;
   }

   @Version
   @Column(name = "version")
   public Integer getVersion()
   {
      return this.version;
   }

   public void setVersion(Integer version)
   {
      this.version = version;
   }

   @Column(name = "name")
   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   @Override
   public String toString()
   {
      return name;
   }

}
